# Generated by Django 4.2.11 on 2024-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristdestination',
            name='landmark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristdestination',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='touristdestination',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_destination_images/'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
