# Generated by Django 4.2.11 on 2024-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_touristdestination_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristdestination',
            name='google_map_link',
            field=models.URLField(null=True),
        ),
    ]
