# Generated by Django 4.2.11 on 2024-05-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0003_alter_touristdestination_google_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristdestination',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='touristdestination',
            name='weather',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
